INSERT INTO PRODUCTO (id, nombre, descripcion, precio, cantidad) VALUES (1, 'Sandalias Teva', 'Cómodas para el verano', 50.00, 12);
INSERT INTO PRODUCTO (id, nombre, descripcion, precio, cantidad) VALUES (2, 'Zapatillas Nike Air', 'Ideal para corredores y actividades de alto impacto', 120.00, 30);
INSERT INTO PRODUCTO (id, nombre, descripcion, precio, cantidad) VALUES (3, 'Botas de montaña', 'Resistentes y duraderas, perfectas para senderismo', 150.00, 15);
INSERT INTO PRODUCTO (id, nombre, descripcion, precio, cantidad) VALUES (4, 'Mocasines de cuero', 'Elegantes y cómodos para el trabajo diario', 85.00, 20);
INSERT INTO PRODUCTO (id, nombre, descripcion, precio, cantidad) VALUES (5, 'Zapatillas deportivas Adidas', 'Ligeras y flexibles, para deportes y entrenamiento diario', 99.99, 40);
INSERT INTO PRODUCTO (id, nombre, descripcion, precio, cantidad) VALUES (6, 'Chanclas de playa', 'Ligeras y frescas, ideales para el verano', 25.00, 50);
INSERT INTO PRODUCTO (id, nombre, descripcion, precio, cantidad) VALUES (7, 'Zapatos formales', 'Zapatos de vestir para ocasiones especiales', 115.00, 10);
INSERT INTO PRODUCTO (id, nombre, descripcion, precio, cantidad) VALUES (8, 'Botines de invierno', 'Calientes y a prueba de agua, perfectos para el frío', 130.00, 25);
INSERT INTO PRODUCTO (id, nombre, descripcion, precio, cantidad) VALUES (9, 'Sandalias de cuero', 'Cómodas y estilosas para uso diario', 45.00, 35);
INSERT INTO PRODUCTO (id, nombre, descripcion, precio, cantidad) VALUES (10, 'Zapatillas de ballet', 'Suaves y flexibles, diseñadas para bailarines', 65.00, 20);
INSERT INTO PRODUCTO (id, nombre, descripcion, precio, cantidad) VALUES (11, 'Zapatos de golf', 'Con soporte y adherencia para el campo de golf', 110.00, 15);
INSERT INTO PRODUCTO (id, nombre, descripcion, precio, cantidad) VALUES (12, 'Botas de trabajo', 'Fuertes y seguras para entornos de trabajo pesado', 95.00, 20);
INSERT INTO PRODUCTO (id, nombre, descripcion, precio, cantidad) VALUES (13, 'Zapatillas de running minimalistas', 'Para una experiencia de carrera natural', 70.00, 25);
INSERT INTO PRODUCTO (id, nombre, descripcion, precio, cantidad) VALUES (14, 'Zapatos de escalada', 'Para precisión y soporte en escalada deportiva', 120.00, 15);
INSERT INTO PRODUCTO (id, nombre, descripcion, precio, cantidad) VALUES (15, 'Sneakers de moda', 'Tendencia y comodidad en un solo producto', 80.00, 40);
INSERT INTO PRODUCTO (id, nombre, descripcion, precio, cantidad) VALUES (16, 'Zapatillas Nike Air', 'Para salir comodo', 290.00, 10);
INSERT INTO PRODUCTO (id, nombre, descripcion, precio, cantidad) VALUES (17, 'Zapatillas Nike Air', 'Solo talle 44 y con colores rojos', 290.00, 10);
INSERT INTO PRODUCTO (id, nombre, descripcion, precio, cantidad) VALUES (18, 'Zapatillas Nike Air', 'Usadas', 20.00, 5);
